from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ContactBook(object):
    """Class for the main UI, the contact book."""

    def setupUi(self, ContactBook):
        ContactBook.setObjectName("ContactBook")
        ContactBook.resize(420, 413)
        self.CreateButton = QtWidgets.QPushButton(parent=ContactBook)
        self.CreateButton.setGeometry(QtCore.QRect(140, 330, 141, 23))
        self.CreateButton.setObjectName("CreateButton")
        self.CBTitleLabel = QtWidgets.QLabel(parent=ContactBook)
        self.CBTitleLabel.setGeometry(QtCore.QRect(0, 0, 421, 51))
        self.CBTitleLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.CBTitleLabel.setObjectName("CBTitleLabel")
        self.ContactList = QtWidgets.QScrollArea(parent=ContactBook)
        self.ContactList.setGeometry(QtCore.QRect(20, 50, 381, 241))
        self.ContactList.setWidgetResizable(True)
        self.ContactList.setObjectName("ContactList")
        self.ContactListContents = QtWidgets.QWidget()
        self.ContactListContents.setGeometry(QtCore.QRect(0, 0, 379, 239))
        self.ContactListContents.setObjectName("ContactListContents")
        self.ContactList.setWidget(self.ContactListContents)
        self.EditIDSelector = QtWidgets.QSpinBox(parent=ContactBook)
        self.EditIDSelector.setGeometry(QtCore.QRect(130, 370, 62, 22))
        self.EditIDSelector.setObjectName("EditIDSelector")
        self.EditIDButton = QtWidgets.QPushButton(parent=ContactBook)
        self.EditIDButton.setGeometry(QtCore.QRect(200, 370, 91, 23))
        self.EditIDButton.setObjectName("EditIDButton")

        self.retranslateUi(ContactBook)
        QtCore.QMetaObject.connectSlotsByName(ContactBook)

    def retranslateUi(self, ContactBook):
        _translate = QtCore.QCoreApplication.translate
        ContactBook.setWindowTitle(_translate("ContactBook", "Contact Book"))
        self.CreateButton.setText(_translate("ContactBook", "Create New Contact"))
        self.CBTitleLabel.setText(_translate("ContactBook",
                                             "<html><head/><body><p><span style=\" font-size:18pt;\">Contact Book</span></p></body></html>"))
        self.EditIDButton.setText(_translate("ContactBook", "Edit Contact"))


class Ui_CreateContactDialog(object):
    """This class defines the contact creation dialog."""

    def setupUi(self, CreateContactDialog):
        CreateContactDialog.setObjectName("CreateContactDialog")
        CreateContactDialog.resize(400, 419)
        self.C_TitleLabel = QtWidgets.QLabel(parent=CreateContactDialog)
        self.C_TitleLabel.setGeometry(QtCore.QRect(0, 10, 401, 31))
        self.C_TitleLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.C_TitleLabel.setObjectName("C_TitleLabel")
        self.C_ErrorLabel = QtWidgets.QLabel(parent=CreateContactDialog)
        self.C_ErrorLabel.setGeometry(QtCore.QRect(0, 40, 401, 31))
        self.C_ErrorLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.C_ErrorLabel.setObjectName("C_ErrorLabel")
        self.C_FirstNameInput = QtWidgets.QTextEdit(parent=CreateContactDialog)
        self.C_FirstNameInput.setGeometry(QtCore.QRect(30, 90, 330, 30))
        self.C_FirstNameInput.setObjectName("C_FirstNameInput")
        self.C_LastNameInput = QtWidgets.QTextEdit(parent=CreateContactDialog)
        self.C_LastNameInput.setGeometry(QtCore.QRect(30, 140, 330, 30))
        self.C_LastNameInput.setObjectName("C_LastNameInput")
        self.C_PhnNmbrInput = QtWidgets.QTextEdit(parent=CreateContactDialog)
        self.C_PhnNmbrInput.setGeometry(QtCore.QRect(30, 190, 330, 30))
        self.C_PhnNmbrInput.setObjectName("C_PhnNmbrInput")
        self.C_AddrInput = QtWidgets.QTextEdit(parent=CreateContactDialog)
        self.C_AddrInput.setGeometry(QtCore.QRect(30, 240, 330, 30))
        self.C_AddrInput.setObjectName("C_AddrInput")
        self.C_FirstNameLabel = QtWidgets.QLabel(parent=CreateContactDialog)
        self.C_FirstNameLabel.setGeometry(QtCore.QRect(30, 70, 61, 16))
        self.C_FirstNameLabel.setObjectName("C_FirstNameLabel")
        self.C_LastNameLabel = QtWidgets.QLabel(parent=CreateContactDialog)
        self.C_LastNameLabel.setGeometry(QtCore.QRect(30, 120, 61, 16))
        self.C_LastNameLabel.setObjectName("C_LastNameLabel")
        self.C_PhnNmbrLabel = QtWidgets.QLabel(parent=CreateContactDialog)
        self.C_PhnNmbrLabel.setGeometry(QtCore.QRect(30, 170, 81, 16))
        self.C_PhnNmbrLabel.setObjectName("C_PhnNmbrLabel")
        self.C_AddrLabel = QtWidgets.QLabel(parent=CreateContactDialog)
        self.C_AddrLabel.setGeometry(QtCore.QRect(30, 220, 47, 13))
        self.C_AddrLabel.setObjectName("C_AddrLabel")
        self.C_CreateButton = QtWidgets.QPushButton(parent=CreateContactDialog)
        self.C_CreateButton.setGeometry(QtCore.QRect(160, 340, 75, 23))
        self.C_CreateButton.setObjectName("C_CreateButton")

        self.retranslateUi(CreateContactDialog)
        QtCore.QMetaObject.connectSlotsByName(CreateContactDialog)

    def retranslateUi(self, CreateContactDialog):
        _translate = QtCore.QCoreApplication.translate
        CreateContactDialog.setWindowTitle(_translate("CreateContactDialog", "Create Contact"))
        self.C_TitleLabel.setText(_translate("CreateContactDialog",
                                             "<html><head/><body><p><span style=\" font-size:16pt;\">Create New Contact</span></p></body></html>"))
        self.C_ErrorLabel.setText(_translate("CreateContactDialog",
                                             "<html><head/><body><p><span style=\" font-size:10pt;\"> </span></p></body></html>"))
        self.C_FirstNameLabel.setText(_translate("CreateContactDialog", "First Name"))
        self.C_LastNameLabel.setText(_translate("CreateContactDialog", "Last Name"))
        self.C_PhnNmbrLabel.setText(_translate("CreateContactDialog", "Phone Number"))
        self.C_AddrLabel.setText(_translate("CreateContactDialog", "Address"))
        self.C_CreateButton.setText(_translate("CreateContactDialog", "Create "))


class Ui_EditContactDialog(object):
    """This class provides the UI for editing a contact."""

    def setupUi(self, EditContactDialog):
        EditContactDialog.setObjectName("EditContactDialog")
        EditContactDialog.resize(401, 420)
        self.E_EditContactLabel = QtWidgets.QLabel(parent=EditContactDialog)
        self.E_EditContactLabel.setGeometry(QtCore.QRect(0, 2, 401, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.E_EditContactLabel.setFont(font)
        self.E_EditContactLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.E_EditContactLabel.setObjectName("E_EditContactLabel")
        self.E_IDLabel = QtWidgets.QLabel(parent=EditContactDialog)
        self.E_IDLabel.setGeometry(QtCore.QRect(0, 50, 401, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.E_IDLabel.setFont(font)
        self.E_IDLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.E_IDLabel.setObjectName("E_IDLabel")
        self.E_AddressInput = QtWidgets.QTextEdit(parent=EditContactDialog)
        self.E_AddressInput.setGeometry(QtCore.QRect(40, 270, 330, 30))
        self.E_AddressInput.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.E_AddressInput.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.E_AddressInput.setObjectName("E_AddressInput")
        self.E_PhnNbrLabel = QtWidgets.QLabel(parent=EditContactDialog)
        self.E_PhnNbrLabel.setGeometry(QtCore.QRect(40, 200, 150, 16))
        self.E_PhnNbrLabel.setObjectName("E_PhnNbrLabel")
        self.E_PhnNbrInput = QtWidgets.QTextEdit(parent=EditContactDialog)
        self.E_PhnNbrInput.setGeometry(QtCore.QRect(40, 220, 330, 30))
        self.E_PhnNbrInput.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.E_PhnNbrInput.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.E_PhnNbrInput.setObjectName("E_PhnNbrInput")
        self.E_FirstNameLabel = QtWidgets.QLabel(parent=EditContactDialog)
        self.E_FirstNameLabel.setGeometry(QtCore.QRect(40, 100, 61, 16))
        self.E_FirstNameLabel.setObjectName("E_FirstNameLabel")
        self.E_FirstNameInput = QtWidgets.QTextEdit(parent=EditContactDialog)
        self.E_FirstNameInput.setGeometry(QtCore.QRect(40, 120, 330, 30))
        self.E_FirstNameInput.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.E_FirstNameInput.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.E_FirstNameInput.setObjectName("E_FirstNameInput")
        self.E_LastNameLabel = QtWidgets.QLabel(parent=EditContactDialog)
        self.E_LastNameLabel.setGeometry(QtCore.QRect(40, 150, 61, 16))
        self.E_LastNameLabel.setObjectName("E_LastNameLabel")
        self.E_LastNameInput = QtWidgets.QTextEdit(parent=EditContactDialog)
        self.E_LastNameInput.setGeometry(QtCore.QRect(40, 170, 330, 30))
        self.E_LastNameInput.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.E_LastNameInput.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.E_LastNameInput.setObjectName("E_LastNameInput")
        self.E_AddressLabel = QtWidgets.QLabel(parent=EditContactDialog)
        self.E_AddressLabel.setGeometry(QtCore.QRect(40, 250, 61, 16))
        self.E_AddressLabel.setObjectName("E_AddressLabel")
        self.horizontalLayoutWidget = QtWidgets.QWidget(parent=EditContactDialog)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 340, 401, 80))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.E_HorizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.E_HorizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.E_HorizontalLayout.setObjectName("E_HorizontalLayout")
        self.E_SubmitButton = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.E_SubmitButton.sizePolicy().hasHeightForWidth())
        self.E_SubmitButton.setSizePolicy(sizePolicy)
        self.E_SubmitButton.setObjectName("E_SubmitButton")
        self.E_HorizontalLayout.addWidget(self.E_SubmitButton)

        self.retranslateUi(EditContactDialog)
        QtCore.QMetaObject.connectSlotsByName(EditContactDialog)

    def retranslateUi(self, EditContactDialog):
        _translate = QtCore.QCoreApplication.translate
        EditContactDialog.setWindowTitle(_translate("EditContactDialog", "Edit Contact"))
        self.E_EditContactLabel.setText(_translate("EditContactDialog", "Edit Contact"))
        self.E_IDLabel.setText(_translate("EditContactDialog", "ID: <sample>"))
        self.E_PhnNbrLabel.setText(_translate("EditContactDialog", "Phone Number"))
        self.E_FirstNameLabel.setText(_translate("EditContactDialog", "First Name"))
        self.E_LastNameLabel.setText(_translate("EditContactDialog", "Last Name"))
        self.E_AddressLabel.setText(_translate("EditContactDialog", "Address"))
        self.E_SubmitButton.setText(_translate("EditContactDialog", "Submit"))
